### ISSUE TITLE
AAT, I'd like to test Accounts emails using a better method than Guerillamail so that tests aren't dependent on a 3rd party site.

### ISSUE THREAD

**Issue by m1yag1** [openstax/os-automation#14]
We need to explore some other options instead of using Guerillamail. This process here is extremely brittle and not ideal. 

Accounts also has some backend integration tests. They cheat a little bit b/c they know the validation code We may need to discuss with the tutor devs the best way to test this. We need to get the conversation going.

https://github.com/openstax/accounts/blob/master/spec/features/confirm_email_spec.rb.

**Comment by gregfitch** [comment]
I've thought about using the short circuit but decided against it because the unit tests are checking the process, but QA needs to verify the e-mail activity, which will come into play when dealing with Payments.

**Comment by gregfitch** [comment]
see #84
