### ISSUE TITLE
OpenStax Website test cases

### ISSUE THREAD

**Issue by Ashsandra** [openstax/os-automation#42]
https://openstax.testrail.net/index.php?/suites/view/73&group_by=cases:section_id&group_id=14776&group_order=asc

- [x] About Us
- [x] Accessibility
- [x] Adopters
- [x] Adoption
- [x] Blog
- [x] Books
- [x] Bookstore Suppliers
- [x] Careers
- [x] Contact
~~Content Management~~
- [x] Donation
- [x] Errata
- [x] FAQ
- [x] Home
~~Institutional Partnerships~~
- [x] Interest
- [x] Legal
- [x] OS Tutor Marketing
- [x] Our Impact
- [x] Partners
- [x] Press
- [x] Privacy
- [x] Research
- [x] Subjects
- [x] Supporters and Foundations
- [x] Team
- [x] Technology
- [x] Terms

**Comment by gregfitch** [comment]
- [ ] About Us
- [ ] Accessibility
- [ ] Content Management
- [ ] Adopters
- [ ] Blog
- [ ] Books
- [ ] Careers
- [ ] Contact
- [ ] Donation
- [ ] FAQ
- [ ] Home
- [ ] Institutional Partnerships
- [ ] Legal
- [ ] Tutor Marketing
- [ ] Impact
- [ ] Partners
- [ ] Press
- [ ] Privacy
- [ ] Research
- [ ] Subjects
- [ ] Supporters and Foundations
- [ ] Team
- [ ] Technology
- [ ] Terms

**Comment by m1yag1** [comment]
Moving to blocked pipeline
