### ISSUE TITLE
Accounts - Get and set a username

### ISSUE THREAD

**Issue by m1yag1** [openstax/os-automation#52]
@m1yag1 commented on [Thu Jul 12 2018](https://github.com/openstax/quality-assurance-meta/issues/54)

# CASE NUM: C195551
## Section

Accounts > Profile

## User story

AAT, I'd like an automated test that asserts Get and set a username

## Preconditions

1. a user with a username is viewing their profile

## Steps

1. Click on the username
2. Change the username text
3. Click the checkmark to save the changes
4. Click on the new username
5. Revert the username
6. Click the checkmark to save the changes

## Expected Result

1. The username was changed following step 3
2. The username was changed back following step 6

**Comment by gregfitch** [comment]
Issue covered on master
