### ISSUE TITLE
Accounts - Sign up as a Facebook user

### ISSUE THREAD

**Issue by m1yag1** [openstax/os-automation#54]
@m1yag1 commented on [Thu Jul 12 2018](https://github.com/openstax/quality-assurance-meta/issues/65)

# CASE NUM: C200745
## Section

Accounts > Signup

## User story

AAT, I'd like an automated test that asserts Sign up as a Facebook user

## Preconditions

1. a valid Facebook account
2. the Accounts Home page is loaded

## Steps

1. click the "Sign up here." link
2. select "Student" from the drop down menu
3. enter the email associated with the Facebook account
4. enter the PIN code from the Accounts verification email and click the "CONFIRM" button
5. click the "Sign up with Google or Facebook instead." link
6. click the "Facebook" button
7. log into Facebook
8. enter a school name
9. click the checkbox next to "I agree to the Terms of Use and the Privacy Policy." and click the "CREATE ACCOUNT" button

## Expected Result

1. the profile for the new account is displayed

**Comment by gregfitch** [comment]
#107
