### ISSUE TITLE
Accounts - Login using Google

### ISSUE THREAD

**Issue by m1yag1** [openstax/os-automation#63]
@m1yag1 commented on [Thu Jul 12 2018](https://github.com/openstax/quality-assurance-meta/issues/58)

# CASE NUM: C195555
## Section

Accounts > Profile

## User story

AAT, I'd like an automated test that asserts Login using Google

## Preconditions

1. a valid Google Gmail email and password
2. a user with that email and Google authentication enabled
3. the Accounts Home page is loaded

## Steps

1. enter the Gmail address and click "NEXT"
2. click the "Log in with Google" button

## Expected Result

1. the user is logged in

**Comment by gregfitch** [comment]
Altered the test to use a global Gmail account osttutor.test@gmail.com with a corresponding Facebook account and Accounts student user (Olivia Kapua).

**Comment by gregfitch** [comment]
#107
