### ISSUE TITLE
Accounts - Add a verified e-mail to a profile

### ISSUE THREAD

**Issue by m1yag1** [openstax/os-automation#64]
@m1yag1 commented on [Thu Jul 12 2018](https://github.com/openstax/quality-assurance-meta/issues/57)

# CASE NUM: C195553
## Section

Accounts > Profile

## User story

AAT, I'd like an automated test that asserts Add a verified e-mail to a profile

## Preconditions

1. a user viewing their Accounts Profile
2. a new, accessible email

## Steps

1. click the "Add an email" link
2. enter the email in the input box
3. click the checkmark
4. go to the email inbox to view the confirmation email and click the confirmation URL
5. close the new tab
6. reload the Accounts profile page

## Expected Result

1. the email no longer shows "unconfirmed" to the right

**Comment by gregfitch** [comment]
#107
