### ISSUE TITLE
Accounts - Verify an e-mail

### ISSUE THREAD

**Issue by m1yag1** [openstax/os-automation#65]
@m1yag1 commented on [Thu Jul 12 2018](https://github.com/openstax/quality-assurance-meta/issues/56)

# CASE NUM: C195554
## Section

Accounts > Profile

## User story

AAT, I'd like an automated test that asserts Verify an e-mail

## Preconditions

1. a user viewing their Accounts Profile
2. a new, accessible email

## Steps

1. click on the unconfirmed email
2. click the "Resend confirmation email" link
3. view the confirmation email and click the confirmation URL
4. close the new tab
5. reload the Accounts profile page

## Expected Result

1. a verification message "A verification message has been sent to <email>" shows above the email after clicking the resend link
2. the email no longer shows "unconfirmed" to the right

**Comment by gregfitch** [comment]
#107
