### ISSUE TITLE
Accounts - Get current e-mails and their status

### ISSUE THREAD

**Issue by m1yag1** [openstax/os-automation#66]
@m1yag1 commented on [Thu Jul 12 2018](https://github.com/openstax/quality-assurance-meta/issues/55)

# CASE NUM: C195552
## Section

Accounts > Profile

## User story

AAT, I'd like an automated test that asserts Get current e-mails and their status

## Preconditions

1. a user viewing their profile

## Steps

1. Click "Add an email"
2. Enter an email (real or fake)
3. Click the checkmark to save the email
4. Click the new email
5. Click the "Delete" link
6. Click the "OK" button to confirm the deletion

## Expected Result

1. The new email is saved following step 3
2. The new email is listed as "unconfirmed"
3. The new email is not shown following step 6

**Comment by gregfitch** [comment]
#107
